apiVersion: apps/v1
kind: Deployment
metadata:
  name: horoscopo
spec:
  selector:
    matchLabels:
      app: horoscopo
  template:
    metadata:
      labels:
        app: horoscopo
    spec:
      containers:
      - name: horoscopo
        image: jaqueline4444/horoscopo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: horoscopo-service
spec:
  selector:
    app: horoscopo
  ports:
  - port: 6379
    targetPort: 6379

